// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2C1Em8BdB7GacrOXsH1RveHWNgD9q9Sc',
    appId: '1:942025057583:android:ed3107cb78b747d5256dda',
    messagingSenderId: '942025057583',
    projectId: 'mochat-5ebe2',
    storageBucket: 'mochat-5ebe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBciHE6G-aPYaXEUaUH1d89_-l1r1oxaGc',
    appId: '1:942025057583:ios:90d89b13693cfb47256dda',
    messagingSenderId: '942025057583',
    projectId: 'mochat-5ebe2',
    storageBucket: 'mochat-5ebe2.appspot.com',
    androidClientId: '942025057583-50d69v6ptb8m844kgl4cv09q127k1so3.apps.googleusercontent.com',
    iosClientId: '942025057583-040lvkvu852hm6lpn88co4sk8srsppg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mohachat.mohaChat',
  );
}
